"""
List of FHIR ndjson to dict transformers
"""

from radiant_fhir_transform_cli.transform.classes.document_reference import (
    DocumentReferenceAuthorTransformer,
    DocumentReferenceContentTransformer,
    DocumentReferenceIdentifierTransformer,
    DocumentReferenceTransformer,
    DocumentReferenceTypeCodingTransformer,
)
from radiant_fhir_transform_cli.transform.classes.observation import (
    ObservationBasedOnTransformer,
    ObservationCategoryCodingTransformer,
    ObservationComponentTransformer,
    ObservationExtensionTransformer,
    ObservationNoteTransformer,
    ObservationPerformerTransformer,
    ObservationTransformer,
    ObservationValueCodeableConceptCodingTransformer,
)
from radiant_fhir_transform_cli.transform.classes.observation.observation_code_coding import (
    ObservationCodeCodingTransformer,
)
from radiant_fhir_transform_cli.transform.classes.patient import (
    PatientTransformer,
)

from radiant_fhir_transform_cli.transform.classes.service_request import (
    ServiceRequestTransformer,
    ServiceRequestCodeCodingTransformer,
    ServiceRequestReasonCodeTransformer,
    ServiceRequestContainedTransformer,
    ServiceRequestIdentifierTransformer,
    ServiceRequestPerformerTransformer,
    ServiceRequestSupportingInfoTransformer,
    ServiceRequestSpecimenTransformer,
    ServiceRequestNoteTransformer,
    ServiceRequestInstantiatesUriTransformer,
    ServiceRequestBasedOnTransformer,
    ServiceRequestReplacesTransformer,
    ServiceRequestCategoryTransformer,
    ServiceRequestOrderDetailTransformer,
    ServiceRequestLocationCodeTransformer,
    ServiceRequestLocationReferenceTransformer,
    ServiceRequestReasonReferenceTransformer,
    ServiceRequestInsuranceTransformer,
    ServiceRequestBodySiteTransformer,
    ServiceRequestRelevantHistoryTransformer,
    ServiceRequestPerformerTypeCodingTransformer,
)

from radiant_fhir_transform_cli.transform.classes.medication import (
    MedicationTransformer,
    MedicationIdentifierTransformer,
    MedicationCodeCodingTransformer,
    MedicationFormCodingTransformer,
    MedicationIngredientTransformer,
)
from radiant_fhir_transform_cli.transform.classes.medication_request import (
    MedicationRequestTransformer,
    MedicationRequestIdentifierTransformer,
    MedicationRequestStatusReasonCodingTransformer,
    MedicationRequestCategoryTransformer,
    MedicationRequestMedicationCodeableConceptCodingTransformer,
    MedicationRequestSupportingInformationTransformer,
    MedicationRequestPerformerTypeCodingTransformer,
    MedicationRequestReasonCodeTransformer,
    MedicationRequestReasonReferenceTransformer,
    MedicationRequestInstantiatesCanonicalTransformer,
    MedicationRequestInstantiatesUriTransformer,
    MedicationRequestBasedOnTransformer,
    MedicationRequestCourseOfTherapyTypeCodingTransformer,
    MedicationRequestInsuranceTransformer,
    MedicationRequestNoteTransformer,
    MedicationRequestDosageInstructionTransformer,
    MedicationRequestSubstitutionAllowedCodeableConceptCodingTransformer,
    MedicationRequestSubstitutionReasonCodingTransformer,
    MedicationRequestDetectedIssueTransformer,
    MedicationRequestEventHistoryTransformer,
)
from radiant_fhir_transform_cli.transform.classes.procedure import (
    ProcedureTransformer,
    ProcedureIdentifierTransformer,
    ProcedureInstantiatesCanonicalTransformer,
    ProcedureInstantiatesUriTransformer,
    ProcedureBasedOnTransformer,
    ProcedurePartOfTransformer,
    ProcedureStatusReasonCodingTransformer,
    ProcedureCategoryCodingTransformer,
    ProcedureCodeCodingTransformer,
    ProcedurePerformerTransformer,
    ProcedureReasonCodeTransformer,
    ProcedureReasonReferenceTransformer,
    ProcedureBodySiteTransformer,
    ProcedureOutcomeCodingTransformer,
    ProcedureReportTransformer,
    ProcedureComplicationTransformer,
    ProcedureComplicationDetailTransformer,
    ProcedureFollowUpTransformer,
    ProcedureNoteTransformer,
    ProcedureFocalDeviceTransformer,
    ProcedureUsedReferenceTransformer,
    ProcedureUsedCodeTransformer,
)
from radiant_fhir_transform_cli.transform.classes.specimen import (
    SpecimenTransformer,
    SpecimenCollectionBodySiteCodingTransformer,
    SpecimenCollectionFastingStatusCodeableConceptCodingTransformer,
    SpecimenTypeCodingTransformer,
    SpecimenConditionTransformer,
    SpecimenContainerTransformer,
    SpecimenCollectionMethodCodingTransformer,
    SpecimenParentTransformer,
    SpecimenProcessingTransformer,
    SpecimenRequestTransformer,
    SpecimenNoteTransformer,
    SpecimenIdentifierTransformer,
)
from radiant_fhir_transform_cli.transform.classes.location import (
    LocationTransformer,
    LocationIdentifierTransformer,
    LocationAliasTransformer,
    LocationTypeTransformer,
    LocationTelecomTransformer,
    LocationPhysicalTypeCodingTransformer,
    LocationHoursOfOperationTransformer,
    LocationEndpointTransformer,
)
from radiant_fhir_transform_cli.transform.classes.organization import (
    OrganizationTransformer,
    OrganizationIdentifierTransformer,
    OrganizationTypeTransformer,
    OrganizationAliasTransformer,
    OrganizationTelecomTransformer,
    OrganizationAddressTransformer,
    OrganizationContactTransformer,
    OrganizationEndpointTransformer,
)

from radiant_fhir_transform_cli.transform.classes.diagnostic_report import (
    DiagnosticReportIdentifierTransformer,
    DiagnosticReportTransformer,
    DiagnosticReportBasedOnTransformer,
    DiagnosticReportCategoryTransformer,
    DiagnosticReportCodeCodingTransformer,
    DiagnosticReportPerformerTransformer,
    DiagnosticReportResultTransformer,
    DiagnosticReportPresentedFormTransformer,
    DiagnosticReportConclusionCodeTransformer,
    DiagnosticReportMediaTransformer,
    DiagnosticReportImagingStudyTransformer,
    DiagnosticReportResultsInterpreterTransformer,
    DiagnosticReportSpecimenTransformer,
)

from radiant_fhir_transform_cli.transform.classes.allergy_intolerance import (
    AllergyIntoleranceTransformer,
    AllergyIntoleranceClinicalStatusCodingTransformer,
    AllergyIntoleranceVerificationStatusCodingTransformer,
    AllergyIntoleranceCategoryTransformer,
    AllergyIntoleranceCodeCodingTransformer,
    AllergyIntoleranceNoteTransformer,
    AllergyIntoleranceReactionTransformer,
)

# Map FHIR resource type to its transformer class
transformers = {
    "Patient": [PatientTransformer],
    "Observation": [
        ObservationTransformer,
        ObservationCategoryCodingTransformer,
        ObservationCodeCodingTransformer,
        ObservationComponentTransformer,
        ObservationExtensionTransformer,
        ObservationNoteTransformer,
        ObservationPerformerTransformer,
        ObservationValueCodeableConceptCodingTransformer,
        ObservationBasedOnTransformer,
    ],
    "DocumentReference": [
        DocumentReferenceTransformer,
        DocumentReferenceContentTransformer,
        DocumentReferenceTypeCodingTransformer,
        DocumentReferenceIdentifierTransformer,
        DocumentReferenceAuthorTransformer,
    ],
    "Medication": [
        MedicationTransformer,
        MedicationIdentifierTransformer,
        MedicationCodeCodingTransformer,
        MedicationFormCodingTransformer,
        MedicationIngredientTransformer,
    ],
    "ServiceRequest": [
        ServiceRequestTransformer,
        ServiceRequestCodeCodingTransformer,
        ServiceRequestReasonCodeTransformer,
        ServiceRequestContainedTransformer,
        ServiceRequestIdentifierTransformer,
        ServiceRequestPerformerTransformer,
        ServiceRequestSupportingInfoTransformer,
        ServiceRequestSpecimenTransformer,
        ServiceRequestNoteTransformer,
        ServiceRequestInstantiatesUriTransformer,
        ServiceRequestBasedOnTransformer,
        ServiceRequestReplacesTransformer,
        ServiceRequestCategoryTransformer,
        ServiceRequestOrderDetailTransformer,
        ServiceRequestLocationCodeTransformer,
        ServiceRequestLocationReferenceTransformer,
        ServiceRequestReasonReferenceTransformer,
        ServiceRequestInsuranceTransformer,
        ServiceRequestBodySiteTransformer,
        ServiceRequestRelevantHistoryTransformer,
        ServiceRequestPerformerTypeCodingTransformer,
    ],
    "Specimen": [
        SpecimenTransformer,
        SpecimenCollectionBodySiteCodingTransformer,
        SpecimenCollectionFastingStatusCodeableConceptCodingTransformer,
        SpecimenTypeCodingTransformer,
        SpecimenConditionTransformer,
        SpecimenContainerTransformer,
        SpecimenCollectionMethodCodingTransformer,
        SpecimenParentTransformer,
        SpecimenProcessingTransformer,
        SpecimenRequestTransformer,
        SpecimenNoteTransformer,
        SpecimenIdentifierTransformer,
    ],
    "MedicationRequest": [
        MedicationRequestTransformer,
        MedicationRequestIdentifierTransformer,
        MedicationRequestStatusReasonCodingTransformer,
        MedicationRequestCategoryTransformer,
        MedicationRequestMedicationCodeableConceptCodingTransformer,
        MedicationRequestSupportingInformationTransformer,
        MedicationRequestPerformerTypeCodingTransformer,
        MedicationRequestReasonCodeTransformer,
        MedicationRequestReasonReferenceTransformer,
        MedicationRequestInstantiatesCanonicalTransformer,
        MedicationRequestInstantiatesUriTransformer,
        MedicationRequestBasedOnTransformer,
        MedicationRequestCourseOfTherapyTypeCodingTransformer,
        MedicationRequestInsuranceTransformer,
        MedicationRequestNoteTransformer,
        MedicationRequestDosageInstructionTransformer,
        MedicationRequestSubstitutionAllowedCodeableConceptCodingTransformer,
        MedicationRequestSubstitutionReasonCodingTransformer,
        MedicationRequestDetectedIssueTransformer,
        MedicationRequestEventHistoryTransformer,
    ],
    "DiagnosticReport": [
        DiagnosticReportIdentifierTransformer,
        DiagnosticReportTransformer,
        DiagnosticReportBasedOnTransformer,
        DiagnosticReportCategoryTransformer,
        DiagnosticReportCodeCodingTransformer,
        DiagnosticReportPerformerTransformer,
        DiagnosticReportResultTransformer,
        DiagnosticReportPresentedFormTransformer,
        DiagnosticReportConclusionCodeTransformer,
        DiagnosticReportMediaTransformer,
        DiagnosticReportImagingStudyTransformer,
        DiagnosticReportResultsInterpreterTransformer,
        DiagnosticReportSpecimenTransformer,
    ],
    "Location": [
        LocationTransformer,
        LocationIdentifierTransformer,
        LocationAliasTransformer,
        LocationTypeTransformer,
        LocationTelecomTransformer,
        LocationPhysicalTypeCodingTransformer,
        LocationHoursOfOperationTransformer,
        LocationEndpointTransformer,
    ],
    "Organization": [
        OrganizationTransformer,
        OrganizationIdentifierTransformer,
        OrganizationTypeTransformer,
        OrganizationAliasTransformer,
        OrganizationTelecomTransformer,
        OrganizationAddressTransformer,
        OrganizationContactTransformer,
        OrganizationEndpointTransformer,
    ],
    "Procedure": [
        ProcedureTransformer,
        ProcedureIdentifierTransformer,
        ProcedureInstantiatesCanonicalTransformer,
        ProcedureInstantiatesUriTransformer,
        ProcedureBasedOnTransformer,
        ProcedurePartOfTransformer,
        ProcedureStatusReasonCodingTransformer,
        ProcedureCategoryCodingTransformer,
        ProcedureCodeCodingTransformer,
        ProcedurePerformerTransformer,
        ProcedureReasonCodeTransformer,
        ProcedureReasonReferenceTransformer,
        ProcedureBodySiteTransformer,
        ProcedureOutcomeCodingTransformer,
        ProcedureReportTransformer,
        ProcedureComplicationTransformer,
        ProcedureComplicationDetailTransformer,
        ProcedureFollowUpTransformer,
        ProcedureNoteTransformer,
        ProcedureFocalDeviceTransformer,
        ProcedureUsedReferenceTransformer,
        ProcedureUsedCodeTransformer,
    ],
    "AllergyIntolerance": [
        AllergyIntoleranceTransformer,
        AllergyIntoleranceClinicalStatusCodingTransformer,
        AllergyIntoleranceVerificationStatusCodingTransformer,
        AllergyIntoleranceCategoryTransformer,
        AllergyIntoleranceCodeCodingTransformer,
        AllergyIntoleranceNoteTransformer,
        AllergyIntoleranceReactionTransformer,
    ],
}
