from .related_person import RelatedPersonTransformer
from .related_person_identifier import RelatedPersonIdentifierTransformer
from .related_person_relationship import RelatedPersonRelationshipTransformer
from .related_person_name import RelatedPersonNameTransformer
from .related_person_telecom import RelatedPersonTelecomTransformer
from .related_person_address import RelatedPersonAddressTransformer
from .related_person_photo import RelatedPersonPhotoTransformer
from .related_person_communication import RelatedPersonCommunicationTransformer
